### ISSUE TITLE
Unable to complete installation with civibuild

### ISSUE THREAD

**Issue by mchughbri** [nickperkins/civicrm-buildkit-ddev#1]
I'm running DDEV on WSL using docker-ce and have tried to follow the installation instructions. However, after a successfull `ddev start` I cannot get any further. 

When trying to run:

`ddev exec civibuild create drupal10-clean
`

I get an error of:

`bash: line 1: civibuild: command not found
Failed to execute command civibuild create drupal10-clean: exit status 127`

**Comment by nickperkins** [comment]
@mchughbri Which version of ddev are you using? Using 1.22.7 with a fresh copy of the repository I'm unable to replicate this so far.

Do any errors or other information appears during the `ddev start` process?

**Comment by mchughbri** [comment]
Thanks @nickperkins 

It's ddev version `v1.18.2`. 

No other errors upon `ddev start` here's my output:

$ ddev start
Starting civicrm-buildkit-ddev...
Container ddev-ssh-agent  Creating
Container ddev-ssh-agent  Created
Container ddev-ssh-agent  Starting
Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Using custom apache configuration in /home/user/civicrm-buildkit-ddev/.ddev/apache/apache-site.conf
Custom configuration takes effect when container is created,
usually on start, use 'ddev restart' if you're not seeing it take effect.
Pushed mkcert rootca certs to ddev-global-cache/mkcert
Container ddev-civicrm-buildkit-ddev-db  Creating
Container ddev-civicrm-buildkit-ddev-db  Created
Container ddev-civicrm-buildkit-ddev-web  Creating
Container ddev-civicrm-buildkit-ddev-dba  Creating
Container ddev-civicrm-buildkit-ddev-web  Created
Container ddev-civicrm-buildkit-ddev-dba  Created
Container ddev-civicrm-buildkit-ddev-db  Starting
Container ddev-civicrm-buildkit-ddev-db  Started
Container ddev-civicrm-buildkit-ddev-web  Starting
Container ddev-civicrm-buildkit-ddev-dba  Starting
Container ddev-civicrm-buildkit-ddev-web  Started
Container ddev-civicrm-buildkit-ddev-dba  Started
Container ddev-router  Creating
Container ddev-router  Created
Container ddev-router  Starting
Container ddev-router  Started
User-managed /home/user/civicrm-buildkit-ddev/.ddev/.gitignore will not be managed/overwritten by ddev
Project type has no settings paths configured, so not creating settings file.
User-managed /home/user/civicrm-buildkit-ddev/.ddev/.gitignore will not be managed/overwritten by ddev
Project type has no settings paths configured, so not creating settings file.
Successfully started civicrm-buildkit-ddev
Project can be reached at https://civicrm-buildkit-ddev.ddev.site https://*.civicrm.ddev.site https://127.0.0.1:{portNo}`

**Comment by nickperkins** [comment]
Looking at the ddev release notes, I suspect it won't work with a version older than 1.19.3, but I would recommend upgrading to the latest ddev version and giving that a shot.

This tooling relies on the functionality released in 1.19.3 that enables the use of multiple Dockerfile for the web build.

**Comment by mchughbri** [comment]
That indeed was the problem. An upgrade of `ddev` solved it.  Thanks.
